repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^api/
      - id: ruff-format
        files: ^api/

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'cd web && npx prettier --write --ignore-unknown "${@#web/}"' --
        language: system
        files: ^web/.*\.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^web/(client|\.next)/

      - id: eslint
        name: eslint
        entry: bash -c 'cd web && npx eslint --fix'
        language: system
        files: ^web/.*\.(js|jsx|ts|tsx)$
        exclude: ^web/(client|\.next)/
        pass_filenames: false
